#!/usr/bin/env python3

import sys
from math import sqrt

def read_numbers(file_name):
    with open(file_name, "r") as file:
        numbers = [int(line.strip()) for line in file]
    return numbers

def factorize(n):
    i = 2
    while i <= sqrt(n):
        if n % i == 0:
            print("{} = {} * {}".format(n, i, n // i))
            return
        i += 1
    print("{} = {} * {}".format(n, n, 1))

def factorize_numbers(numbers):
    for num in numbers:
        factorize(num)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)
    numbers = read_numbers(sys.argv[1])
    factorize_numbers(numbers)
