#!/bin/bash

check_factor() 
{
    if [ $# -eq 3 ]; 
    then
        num1=$2
        num2=$3
    else
        num1=$(echo $@ | cut -d' ' -f2)
        num2=$(echo $@ | cut -d' ' -f3- | awk '{for(i=1;i<=NF;i++){if(i!=NF){printf $i "*"}else{printf $i}}}')
    fi

    if (( num2 > num1 )); then
        tmp=$num1
        num1=$num2
        num2=$tmp
    fi

    echo "$1=$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

input_file=$1

while read -r number; do
    factors=$(factor $number)
    check_factor $factors
done < "$input_file"
