#!/usr/bin/python3
import sys

def factorize(number):
    factors = []
    for i in range(2, number):
        if number % i == 0:
            factors.append((i, number // i))
            break
    return factors

def main(input_file):
    output_file = "factorization.txt"
    with open(input_file, 'r') as f_in, open(output_file, 'w') as f_out:
        for line in f_in:
            number = int(line.strip())
            factor_pairs = factorize(number)
            for factor_pair in factor_pairs:
                f_out.write(f"{number}={factor_pair[0]}*{factor_pair[1]}\n")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)
    input_file = sys.argv[1]
    main(input_file)
