#!/usr/bin/python3
import sys

def prime_factors(n):
    factors = []
    divisor = 2
    while n > 1:
        if n % divisor == 0:
            factors.append(divisor)
            n //= divisor
        else:
            divisor += 1
    return factors

def main(filename):
    try:
        with open(filename) as f:
            for line in f:
                num = int(line.strip())
                factors = prime_factors(num)
                print("{}={}".format(num, "*".join(map(str, factors))))
    except FileNotFoundError:
        print("Error: File not found.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <filename>".format(sys.argv[0]))
    else:
        main(sys.argv[1])
